import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const webDir = process.env.SCRUMBOY_WEB_DIR
  ? path.resolve(process.env.SCRUMBOY_WEB_DIR)
  : path.resolve(__dirname, "..");
const localesDir = path.join(webDir, "modules", "i18n", "locales");
const i18nIndexPath = path.join(webDir, "modules", "i18n", "index.ts");
const templatePath = path.join(webDir, "landing.template.html");
const englishLandingPath = path.join(webDir, "landing.html");
const localizedLandingDir = path.join(webDir, "landing.locales");
const checkOnly = process.argv.includes("--check");

const SITE_ORIGIN = "https://scrumboy.com";
const GENERATED_COMMENT = "<!-- Generated by scripts/generate-landing.mjs; edit landing.template.html and locale catalogs. -->";
const SLOT_TAGLINE_KEY = "landing.features.multilingual.slotTagline";
const MULTILINGUAL_TEXT_KEY = "landing.features.multilingual.text";
const MULTILINGUAL_ARIA_KEY = "landing.features.multilingual.imageAriaLabel";
const LOCALIZED_LANDING_HERO_LOCALES = new Set(["ar", "hi", "ur"]);
const LOCALIZED_LANDING_HERO_KEYS = [
  "landing.hero.title.line1Rest",
  "landing.hero.title.line2",
];
const FEATURE_ARTICLE_RE = /<article class="feature" data-feature="[^"]+">[\s\S]*?<\/article>/g;

const INTL_LOCALES = {
  en: "en",
  zh: "zh-CN",
  hi: "hi-IN",
  es: "es-MX",
  ar: "ar",
  fr: "fr",
  pt: "pt-BR",
  id: "id-ID",
  ur: "ur-PK",
  ru: "ru",
  de: "de",
  ja: "ja",
  vi: "vi",
  tr: "tr",
  ko: "ko",
  it: "it-IT",
  th: "th-TH",
};

const OG_LOCALES = {
  en: "en_US",
  zh: "zh_CN",
  hi: "hi_IN",
  es: "es_MX",
  ar: "ar_SA",
  fr: "fr_FR",
  pt: "pt_BR",
  id: "id_ID",
  ur: "ur_PK",
  ru: "ru_RU",
  de: "de_DE",
  ja: "ja_JP",
  vi: "vi_VN",
  tr: "tr_TR",
  ko: "ko_KR",
  it: "it_IT",
  th: "th_TH",
};

// Landing pages stay LTR: localized copy is mostly English for now (in-app RTL unchanged).
const LANDING_RTL_LOCALES = new Set([]);

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function readPublicLocales(source) {
  const match = source.match(/export const PUBLIC_LOCALES = \[([^\]]+)\] as const;/);
  if (!match) {
    throw new Error(`Cannot locate PUBLIC_LOCALES in ${i18nIndexPath}`);
  }
  return [...match[1].matchAll(/"([^"]+)"/g)].map((locale) => locale[1]);
}

function validateLocaleMetadata(publicLocales) {
  const missingIntl = publicLocales.filter((locale) => !INTL_LOCALES[locale]);
  const missingOg = publicLocales.filter((locale) => !OG_LOCALES[locale]);
  const extraIntl = Object.keys(INTL_LOCALES).filter((locale) => !publicLocales.includes(locale));
  const extraOg = Object.keys(OG_LOCALES).filter((locale) => !publicLocales.includes(locale));
  const failures = [];
  if (missingIntl.length > 0) failures.push(`missing INTL_LOCALES: ${missingIntl.join(", ")}`);
  if (missingOg.length > 0) failures.push(`missing OG_LOCALES: ${missingOg.join(", ")}`);
  if (extraIntl.length > 0) failures.push(`extra INTL_LOCALES: ${extraIntl.join(", ")}`);
  if (extraOg.length > 0) failures.push(`extra OG_LOCALES: ${extraOg.join(", ")}`);
  if (publicLocales.includes("pseudo")) failures.push("pseudo must not be in PUBLIC_LOCALES");
  if (publicLocales[0] !== "en") failures.push("PUBLIC_LOCALES must keep en first for x-default/canonical generation");
  if (failures.length > 0) {
    throw new Error(`Landing locale metadata is out of sync:\n- ${failures.join("\n- ")}`);
  }
}

async function readCatalog(locale) {
  const raw = await fs.readFile(path.join(localesDir, `${locale}.json`), "utf8");
  return JSON.parse(raw);
}

function landingUrl(locale) {
  return locale === "en" ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}/${locale}/`;
}

function renderHeadMeta(locale, catalog, publicLocales) {
  const title = escapeHtml(catalog["landing.meta.title"]);
  const description = escapeHtml(catalog["landing.meta.description"]);
  const canonicalUrl = landingUrl(locale);
  const alternateLinks = publicLocales.map((alternateLocale) => (
    `<link rel="alternate" hreflang="${INTL_LOCALES[alternateLocale]}" href="${landingUrl(alternateLocale)}" />`
  ));
  alternateLinks.push(`<link rel="alternate" hreflang="x-default" href="${SITE_ORIGIN}/" />`);

  const ogLocaleAlternates = publicLocales
    .filter((alternateLocale) => alternateLocale !== locale)
    .map((alternateLocale) => `<meta property="og:locale:alternate" content="${OG_LOCALES[alternateLocale]}" />`);

  return [
    `<link rel="canonical" href="${canonicalUrl}" />`,
    ...alternateLinks,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:site_name" content="Scrumboy" />`,
    `<meta property="og:url" content="${canonicalUrl}" />`,
    `<meta property="og:title" content="${title}" />`,
    `<meta property="og:description" content="${description}" />`,
    `<meta property="og:image" content="${SITE_ORIGIN}/og-image.png" />`,
    `<meta property="og:image:width" content="1200" />`,
    `<meta property="og:image:height" content="630" />`,
    `<meta property="og:image:type" content="image/png" />`,
    `<meta property="og:locale" content="${OG_LOCALES[locale]}" />`,
    ...ogLocaleAlternates,
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<meta name="twitter:title" content="${title}" />`,
    `<meta name="twitter:description" content="${description}" />`,
    `<meta name="twitter:image" content="${SITE_ORIGIN}/og-image.png" />`,
  ].join("\n  ");
}

function templateKeys(template) {
  return [...template.matchAll(/\{\{t:([^}]+)\}\}/g)].map((match) => match[1]);
}

function assertCatalogHasKeys(locale, catalog, keys) {
  const missing = keys.filter((key) => typeof catalog[key] !== "string");
  if (missing.length > 0) {
    throw new Error(`${locale}.json is missing landing keys: ${missing.join(", ")}`);
  }
}

function landingDisplayCatalog(locale, localeCatalog, englishCatalog, keys) {
  const catalog = { ...localeCatalog };

  for (const key of keys) {
    if (key.startsWith("landing.")) {
      catalog[key] = englishCatalog[key];
    }
  }

  if (LOCALIZED_LANDING_HERO_LOCALES.has(locale)) {
    for (const key of LOCALIZED_LANDING_HERO_KEYS) {
      const value = localeCatalog[key];
      if (typeof value === "string") {
        catalog[key] = value;
      }
    }
  }

  if (locale !== "en") {
    const multilingualText = localeCatalog[MULTILINGUAL_TEXT_KEY]?.trim();
    if (multilingualText) {
      catalog[MULTILINGUAL_TEXT_KEY] = multilingualText;
    }
    const slotTagline = localeCatalog[SLOT_TAGLINE_KEY]?.trim();
    if (slotTagline) {
      catalog[SLOT_TAGLINE_KEY] = slotTagline;
    }
  }

  const slotTagline = catalog[SLOT_TAGLINE_KEY]?.trim();
  if (slotTagline) {
    catalog[MULTILINGUAL_ARIA_KEY] = slotTagline;
  }

  return catalog;
}

function reorderLocalizedFeatureGrid(html) {
  const gridToken = '<div class="feature-grid">';
  const gridOpen = html.indexOf(gridToken);
  if (gridOpen === -1) {
    return html;
  }

  const contentStart = html.indexOf(">", gridOpen) + 1;
  const gridCloseTokens = [
    "\n        </div>\n      </div>\n    </section>",
    "\r\n        </div>\r\n      </div>\r\n    </section>",
  ];
  let gridClose = -1;
  for (const token of gridCloseTokens) {
    gridClose = html.indexOf(token, contentStart);
    if (gridClose !== -1) {
      break;
    }
  }
  if (gridClose === -1) {
    return html;
  }

  const body = html.slice(contentStart, gridClose);
  const articles = [...body.matchAll(FEATURE_ARTICLE_RE)].map((entry) => entry[0]);
  if (articles.length === 0) {
    return html;
  }

  const multilingualIndex = articles.findIndex((article) => article.includes('data-feature="multilingual"'));
  if (multilingualIndex <= 0) {
    return html;
  }

  const [multilingual] = articles.splice(multilingualIndex, 1);
  const reordered = [multilingual, ...articles].join("\n\n          ");
  return `${html.slice(0, contentStart)}\n          ${reordered}${html.slice(gridClose)}`;
}

function renderLanding(template, locale, catalog, publicLocales) {
  let html = template
    .replaceAll("{{htmlLang}}", INTL_LOCALES[locale])
    .replaceAll("{{htmlDirAttr}}", LANDING_RTL_LOCALES.has(locale) ? ' dir="rtl"' : "")
    .replaceAll("{{landingHeadMeta}}", renderHeadMeta(locale, catalog, publicLocales))
    .replace(/\{\{t:([^}]+)\}\}/g, (_match, key) => escapeHtml(catalog[key]));

  html = html.replace("<!doctype html>\n", `<!doctype html>\n${GENERATED_COMMENT}\n`);

  const leftover = html.match(/\{\{(?!VERSION\b)[^}]+\}\}/);
  if (leftover) {
    throw new Error(`Unresolved landing template token for ${locale}: ${leftover[0]}`);
  }
  if (locale !== "en") {
    html = reorderLocalizedFeatureGrid(html);
  }
  return html;
}

async function writeOrCheck(filePath, content, staleFiles) {
  if (!checkOnly) {
    await fs.writeFile(filePath, content, "utf8");
    return;
  }

  let existing = "";
  try {
    existing = await fs.readFile(filePath, "utf8");
  } catch {
    staleFiles.push(filePath);
    return;
  }
  if (existing !== content) {
    staleFiles.push(filePath);
  }
}

async function assertNoStaleExtraFiles(expectedFiles, staleFiles) {
  let entries = [];
  try {
    entries = await fs.readdir(localizedLandingDir, { withFileTypes: true });
  } catch {
    staleFiles.push(localizedLandingDir);
    return;
  }
  const expected = new Set(expectedFiles.map((filePath) => path.basename(filePath)));
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".html")) continue;
    if (!expected.has(entry.name)) {
      staleFiles.push(path.join(localizedLandingDir, entry.name));
    }
  }
}

async function main() {
  const [i18nSource, template] = await Promise.all([
    fs.readFile(i18nIndexPath, "utf8"),
    fs.readFile(templatePath, "utf8"),
  ]);
  const publicLocales = readPublicLocales(i18nSource);
  validateLocaleMetadata(publicLocales);

  const requiredKeys = templateKeys(template);
  const staleFiles = [];
  const expectedLocalizedFiles = [];
  const englishCatalog = await readCatalog("en");
  assertCatalogHasKeys("en", englishCatalog, requiredKeys);

  if (!checkOnly) {
    await fs.rm(localizedLandingDir, { recursive: true, force: true });
    await fs.mkdir(localizedLandingDir, { recursive: true });
  }

  for (const locale of publicLocales) {
    const catalog = await readCatalog(locale);
    assertCatalogHasKeys(locale, catalog, requiredKeys);
    const html = renderLanding(
      template,
      locale,
      landingDisplayCatalog(locale, catalog, englishCatalog, requiredKeys),
      publicLocales,
    );
    const filePath = locale === "en"
      ? englishLandingPath
      : path.join(localizedLandingDir, `${locale}.html`);
    if (locale !== "en") expectedLocalizedFiles.push(filePath);
    await writeOrCheck(filePath, html, staleFiles);
  }

  if (checkOnly) {
    await assertNoStaleExtraFiles(expectedLocalizedFiles, staleFiles);
    if (staleFiles.length > 0) {
      throw new Error(`Localized landing HTML is stale:\n- ${staleFiles.join("\n- ")}`);
    }
  }

  const action = checkOnly ? "Verified" : "Generated";
  console.log(`${action} localized landing HTML for ${publicLocales.length} public locales.`);
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
